spring:
  datasource:
    url: jdbc:postgresql://fitqa-db-dev.czkattcbnkfu.ap-northeast-2.rds.amazonaws.com:5432/fitqa-db-dev
    username: fitqadmin
    password: vltzk123!
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    include: oauth

server:
  port: 8080
