spring:
  datasource:
    url: jdbc:postgresql://fitqa-db-dev.czkattcbnkfu.ap-northeast-2.rds.amazonaws.com:5432/fitqa-db-dev
    username: fitqadmin
    password: vltzk123!
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    include: oauth

server:
  port: 8080

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: AKIAVCWWD3CZLUPTOPUP
      secret-key: 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