version: '3.7'

services:
  postgres-db:
    container_name: fitqa_postgres
    image: 'postgres:13.1-alpine'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fitqa_db
    ports:
    - "5432:5432"

  pgadmin:
    container_name: fitqa_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
    - "5050:80"